name: e2e-cypress
on: [push, pull_request]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      # Corre TODOS los specs en CHROME (evita el error de Electron/tsx)
      - name: Run Cypress on Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false

      # Guarda videos y screenshots como artefactos del run
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*
          if-no-files-found: ignore

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
          if-no-files-found: ignore
